### ISSUE TITLE
Fix links for missing districts

### ISSUE THREAD

**Issue by nfra** [jvargh7/nfhs5_factsheets#1]
There are several missing district fact-sheets that I can help you add if you like! All of Kerala's and Karnataka's district sheets and something like 10-15 addition district sheets had incorrect links in the portal.

**Comment by jvargh7** [comment]
Hi Nathan,

Thanks so much for reaching out. We did manage to parse KA, KL districts and 10 other districts. We haven’t uploaded it yet due to QC pending from our side. Would you be able to keep us posted on any errors you find in the parsed data?

Really appreciate it!
Jithin

**Comment by jvargh7** [comment]
Resolved with the last commit.
